#![allow(unused_imports)]
use super::*;
use wasm_bindgen::prelude::*;
#[wasm_bindgen]
extern "C" {
    # [ wasm_bindgen ( extends = :: js_sys :: Object , js_name = HIDReportItem , typescript_type = "HIDReportItem" ) ]
    #[derive(Debug, Clone, PartialEq, Eq)]
    #[doc = "The `HidReportItem` class."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub type HidReportItem;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = isAbsolute ) ]
    #[doc = "Getter for the `isAbsolute` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/isAbsolute)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn is_absolute(this: &HidReportItem) -> bool;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = isArray ) ]
    #[doc = "Getter for the `isArray` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/isArray)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn is_array(this: &HidReportItem) -> bool;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = isRange ) ]
    #[doc = "Getter for the `isRange` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/isRange)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn is_range(this: &HidReportItem) -> bool;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = hasNull ) ]
    #[doc = "Getter for the `hasNull` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/hasNull)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn has_null(this: &HidReportItem) -> bool;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = usageMinimum ) ]
    #[doc = "Getter for the `usageMinimum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/usageMinimum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn usage_minimum(this: &HidReportItem) -> u32;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = usageMaximum ) ]
    #[doc = "Getter for the `usageMaximum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/usageMaximum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn usage_maximum(this: &HidReportItem) -> u32;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = reportSize ) ]
    #[doc = "Getter for the `reportSize` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/reportSize)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn report_size(this: &HidReportItem) -> u16;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = reportCount ) ]
    #[doc = "Getter for the `reportCount` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/reportCount)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn report_count(this: &HidReportItem) -> u16;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitExponent ) ]
    #[doc = "Getter for the `unitExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_exponent(this: &HidReportItem) -> u32;
    #[cfg(feature = "HidUnitSystem")]
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitSystem ) ]
    #[doc = "Getter for the `unitSystem` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitSystem)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`, `HidUnitSystem`*"]
    pub fn unit_system(this: &HidReportItem) -> HidUnitSystem;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorLengthExponent ) ]
    #[doc = "Getter for the `unitFactorLengthExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorLengthExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_length_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorMassExponent ) ]
    #[doc = "Getter for the `unitFactorMassExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorMassExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_mass_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorTimeExponent ) ]
    #[doc = "Getter for the `unitFactorTimeExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorTimeExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_time_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorTemperatureExponent ) ]
    #[doc = "Getter for the `unitFactorTemperatureExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorTemperatureExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_temperature_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorCurrentExponent ) ]
    #[doc = "Getter for the `unitFactorCurrentExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorCurrentExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_current_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = unitFactorLuminousIntensityExponent ) ]
    #[doc = "Getter for the `unitFactorLuminousIntensityExponent` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/unitFactorLuminousIntensityExponent)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn unit_factor_luminous_intensity_exponent(this: &HidReportItem) -> i8;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = logicalMinimum ) ]
    #[doc = "Getter for the `logicalMinimum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/logicalMinimum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn logical_minimum(this: &HidReportItem) -> i32;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = logicalMaximum ) ]
    #[doc = "Getter for the `logicalMaximum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/logicalMaximum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn logical_maximum(this: &HidReportItem) -> i32;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = physicalMinimum ) ]
    #[doc = "Getter for the `physicalMinimum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/physicalMinimum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn physical_minimum(this: &HidReportItem) -> i32;
    # [ wasm_bindgen ( structural , method , getter , js_class = "HIDReportItem" , js_name = physicalMaximum ) ]
    #[doc = "Getter for the `physicalMaximum` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/HIDReportItem/physicalMaximum)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `HidReportItem`*"]
    pub fn physical_maximum(this: &HidReportItem) -> i32;
}
